version: '3'

services:
  backend:
    build: ./backend
    container_name: wanderlust-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/wanderlust
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: wanderlust-frontend
    ports:
      - "3001:3000"

  mongo:
    image: mongo:4.4
    container_name: wanderlust-mongo
    restart: always
    ports:
      - "27017:27017"
