sonar.projectKey=wanderlust
sonar.projectName=wanderlust

# IMPORTANT: ONLY ACTUAL CODE FOLDERS
sonar.sources=backend,frontend/src

# LANGUAGE FORCE
sonar.language=js

# INCLUDE FILE TYPES
sonar.inclusions=**/*.js,**/*.ts,**/*.tsx

# EXCLUDE USELESS
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

sonar.sourceEncoding=UTF-8
