sonar.projectKey=wanderlust
sonar.projectName=wanderlust

sonar.sources=.

sonar.inclusions=**/*.js,**/*.ts,**/*.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

sonar.sourceEncoding=UTF-8
